import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import App from './App';

afterEach(cleanup)
it("should return right value after click",()=>{
    const {getByTestId,debug} = render(<App/>)
    const nextBtn = getByTestId("nextBtn")
    const prevBtn = getByTestId("prevBtn")
    const question = getByTestId("question")
    const answer = getByTestId("answer")
    fireEvent.click(nextBtn)
    expect(question).toHaveTextContent("where do you Live?")
    fireEvent.click(nextBtn)
    fireEvent.click(prevBtn)
    expect(question).toHaveTextContent("where do you Live?")
    fireEvent.click(nextBtn)
    fireEvent.click(nextBtn)
    fireEvent.click(nextBtn)
    fireEvent.click(nextBtn)
    expect(answer).toHaveTextContent("I am a Web Developer")
}) 

it("should tell right answers to questions ",()=>{
  const {getByTestId,debug} = render(<App/>)
    const nextBtn = getByTestId("nextBtn")
    const prevBtn = getByTestId("prevBtn")
    const question = getByTestId("question")
    const answer = getByTestId("answer")
    expect(answer).toHaveTextContent("Nitish")
    fireEvent.click(nextBtn)
    expect(answer).toHaveTextContent("Bahadurgarh")
    fireEvent.click(nextBtn)
    expect(answer).toHaveTextContent("I am a Web Developer")
    fireEvent.click(nextBtn)
    fireEvent.click(nextBtn)
    fireEvent.click(nextBtn)
    fireEvent.click(nextBtn)
    fireEvent.click(nextBtn)
    expect(answer).toHaveTextContent("I am a Web Developer")
})